name: Build a static renode-demos package
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
          wget -O dotnet-sdk.tar.gz https://download.visualstudio.microsoft.com/download/pr/ce3fd989-b69d-439a-9cac-09ad40597db8/2848d49480b6e7b1b2a18cfa46d724e2/dotnet-sdk-6.0.100-preview.7.21379.14-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf dotnet-sdk.tar.gz -C $HOME/dotnet
          echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
          echo "$HOME/dotnet" >> $GITHUB_PATH

      - name: Build
        run: |
          dotnet publish

      - name: Test
        run: |
          env -i bin/Debug/net6.0/linux-x64/publish/renode-demos test > OUT
          cat OUT
          if [ "$(cat OUT | head -n 1)" != "0: test" ]; then exit 1; fi
          if [ "$(cat OUT | tail -n 1)" != "Done." ]; then exit 1; fi

      - name: Save binary
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: renode-demos
          path: |
            bin/Debug/net6.0/linux-x64/publish/renode-demos
